using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Utilities.ExpressionBuilders
{
    enum EStringSymbolReader
    {
        INTEGER,
        DOUBLE,
        DOUBLE_EXPONENTIAL,
        DOUBLE_EXPONENTIAL_MINUS,
        STRING,
        BLANCKS,
        EQUAL,
        DOUBLE_EQUAL,
        PLUS,
        DOUBLE_PLUS,
        PLUS_EQUAL,
        MINUS,
        DOUBLE_MINUS,
        MINUS_EQUAL,
        TIMES,
        DOUBLE_TIMES,
        TIMES_EQUAL,
        OVER,
        OVER_EQUAL,
        EXPONENTIAL,
        COLON,
        DOUBLE_COLON,
        BITWISE_AND,
        DOUBLE_AND,
        AND_EQUAL,
        BITWISE_OR,
        DOUBLE_OR,
        OR_EQUAL,
        LESS_THAN,
        DOUBLE_LESS,
        TRIPLE_LESS,
        LESS_EQUAL,
        GREAT_THAN,
        DOUBLE_GREAT,
        TRIPLE_GREAT,
        GREAT_EQUAL,
        LEFT_PARENTHESIS,
        RIGHT_PARENTHESIS,
        LEFT_BRACKET,
        RIGHT_BRACKET,
        DOUBLE_QUOTE,
        QUOTE,
        LEFT_BAR,
        SEMI_COLON,
        COMMA,
        TILD,
        HAT,
        QUESTION_MARK,
        EXCLAMATION_MARK,
        LEFT_BRACE,
        RIGHT_BRACE,
        AT,
        CARDINAL,
        DOLLAR,
        POUND,
        CHAPTER,
        EURO,
        ANY
    }
}
